In [12]:
# What are the Escape Characters in python?
print("She said, \"Hello!\"")
print("First Line\nSecond Line")
print("Column1\tColumn2")
print("Backslash: \\")


# | Escape Character | Meaning                       | Example Output              |
# | ---------------- | ----------------------------- | --------------------------- |
# | `\'`             | Single Quote                  | `'It\'s OK' → It's OK`      |
# | `\"`             | Double Quote                  | `"She said \"Hi\""`         |
# | `\\`             | Backslash                     | `'This is a backslash: \\`  |
# | `\n`             | New Line                      | `'Line1\nLine2'`            |
# | `\t`             | Horizontal Tab                | `'A\tB' → A    B`           |
# | `\r`             | Carriage Return               | `'Hello\rWorld'`            |
# | `\b`             | Backspace                     | `'abc\b' → ab`              |
# | `\f`             | Form Feed                     | Rarely used                 |
# | `\a`             | Bell/Alert                    | Makes a beep (may not work) |
# | `\v`             | Vertical Tab                  | Rarely used                 |
# | `\ooo`           | Octal value                   | `\141` → 'a'                |
# | `\xhh`           | Hexadecimal value             | `\x61` → 'a'                |
# | `\uXXXX`         | Unicode 16-bit (4 hex digits) | `\u2764` → ❤️               |
# | `\UXXXXXXXX`     | Unicode 32-bit (8 hex digits) | `\U0001F600` → 😀           |


She said, "Hello!"
First Line
Second Line
Column1	Column2
Backslash: \


In [ ]:
# Which are the different ways to perform string formatting? 
name = "Charlie"
age = 28
print(f"My name is {name} and I am {age} years old.")


In [13]:
# Write a program to print every character of a string entered by the user in a
# new line using a loop
a= input('enter the string:- ')
for i in a:
    print(i)

enter the string:-  roshan


r
o
s
h
a
n


In [3]:
# Write a program to find the length of the string "machine learning" with and
# without using len function
a= 'machine learning'
c=0
for i in a:
    c+=1
c

16

In [15]:
# Write a program to check if the word 'orange' is present in the "This is orange juice".
a = "This is orange juice"
b = 'orange'
if b in a:
    print('yes is present' )

yes is present


In [17]:
# Write a program to find the number of vowels, consonants, digits, and white
# space characters in a string.

a = input('Enter the string')
vowels_cha= 'aeiouAEIOU'

vowels = 0
string = 0
digits = 0
white_space = 0

for i in a:
    if i in vowels_cha:
        vowels+=1
    elif i.isalpha():
        string+=1
    elif i.isdigit():
        digits+=1
    elif i.isspace():
        white_space +=1
print('vowels',vowels)
print('consonants',string)
print('digits',digits)
print('white_space',white_space)        

Enter the string ieow nsfosdjhoe423043


vowels 6
consonants 8
digits 6
white_space 1


In [19]:
#Write a Python program to count Uppercase, Lowercase, special character, and numeric values in a given string.
a ='orhasdnujABSUDH!@#%^1&*'
upper=0
lower=0
digit=0
special=0

for i in a:
    if i.isupper():
        upper+=1
    elif i.islower():
        lower+=1
    elif i.isdigit():
        digit+=1
    else:
        special+=1
print('upper',upper)
print('lower',lower)
print('digit',digit)
print('special',special)

upper 6
lower 9
digit 1
special 7


In [21]:
# Write a program to make a new string with all the consonants deleted from the string "Hello, have a good day".
a= "Hello, have a good day"
vowels= "aeiouAEIOU"
l=[]
for i in a:
    if i not in vowels:
        l.append(i)
print(''.join(l))
        

Hll, hv  gd dy


In [25]:
# Write a Python program to remove the nth index character from a non-empty string.
a= input('enter the string:- ')
b= int(input('enter the removing index:- '))

if b < 0 or b >= len(a):
    print('invalid Index')
else:
    new_text = a[:b]+a[b+1:]
    print(new_text)

enter the string:-  eds
enter the removing index:-  4


invalid Index


In [34]:
# Write a Python program to change a given string to a new string where the first and last characters have been exchanged.
a= 'roshan'
res = a[-1]+a[1:-1] +a[0]
res

'noshar'

In [42]:
# Write a Python program to count the occurrences of each word in a givensentence.
a= 'literalS are fixed values or data that are  date you directly write in you code' 
a= a.lower()
a= a.split()
d={}
for i in a :
    if i in d:
        d[i]+=1
    else:
        d[i]=1
d

{'literals': 1,
 'are': 2,
 'fixed': 1,
 'values': 1,
 'or': 1,
 'data': 1,
 'that': 1,
 'date': 1,
 'you': 2,
 'directly': 1,
 'write': 1,
 'in': 1,
 'code': 1}

In [44]:
# How do you count the occurrence of a given character in a string?
a='roshandabherosandabherere i'
d={}
for i in a :
    if i in d:
        d[i]+=1
    else:
        d[i]=1
d

{'r': 4,
 'o': 2,
 's': 2,
 'h': 3,
 'a': 4,
 'n': 2,
 'd': 2,
 'b': 2,
 'e': 4,
 ' ': 1,
 'i': 1}

In [46]:
# Write a program to find last 10 characters of a string?

a= 'roshandabhere i am from nagpur or yavatmal'
a[-10:]

'r yavatmal'

In [1]:
# WAP to convert a given string to all uppercase if it contains at least 2 uppercase characters in the first 4 characters.
a = 'ROshan'
b = a[:4]
if b[1].isupper():
    print(a.upper())
else:
    print(a)

ROSHAN


In [2]:
# Write a Python program to remove a newline in Python.
text = "  Hello, world!\n  "
clean_text = text.strip()
print(clean_text) 

Hello, world!


'  Hello, world!\n  '

In [19]:
# Write a Python program to swap commas and dots in a string
# ○ Sample string: "32.054,23"
# ○ Expected Output: "32,054.23"

a= '32.054,23'
b = ''

for i in a:
    if i=='.':
        b+=','
    elif i==',':
        b+='.'
    else:
        b+=i
b 

'32,054.23'

In [1]:
# Write a Python program to find the first repeated character in a given string

s= 'roshan dabhere'
count=0
s2=''
firt=''
for i in s:
    if i not in s2:
        s2+=i
        count=0
    elif i in s2:
        print(i)
        break

    

a


In [ ]:
Write a Python program to find the second most repeated word in a given string 
Note=  solving using dic

In [14]:
# Python program to Count Even and Odd numbers in a string

s =' rosan4537290380qsdi9k6ak8'
odd = 0
even=0
for i in s:
    if i.isdigit():
        if int(i)%2 != 0:
            odd+=1
        else:
            even+=1
            
print(odd)
print(even)

6
7


In [16]:
# How do you check if a string contains only digits?
a= input('Enter the value:- ')
if a.isdigit():
    print('All string are Digits:- ',a)
else:
    print('This is not Digits in string:- ',a)

Enter the value:-  ses45


This is not Digits in string:-  ses45


In [20]:
# Write a Python program to remove the characters which have odd index values of a given string

s= 'roshan dabhere'
new_s=''
for i in range(len(s)):
    if i%2 != 0:
        new_s += s[i]
print(new_s)      

ohndbee


In [23]:
# How do you remove a given character/word from String?

s= 'roshanyash'
remov='h'
new_str= ''
for i in s:
    if i not in remov:
        new_str += i
print(new_str)

rosanyas


In [9]:
# reverse string using loop
s = "HelloWorld"
s1=''
for i in s:
    s1= i+s1
s1

'dlroWolleH'

In [10]:
# Write a Python function to reverses a string if its length is a multiple of 5
def reverse(s):

    if len(s) % 5 == 0:
        return s[::-1]
    return s

input_string = "HelloWorld"
result = reverse(input_string)
print(result) 


dlroWolleH


In [16]:
# Write a Python program to format a number with a percentage(0.05 >> 5%)
numbers = [0.05, 0.075, 0.5, 1.0, 0.0025]
value=[]
for i in numbers:
    val= f'{i*100:.0f}%'    
    value.append(val)
print(value)

['5%', '8%', '50%', '100%', '0%']


In [1]:
# Write a Python program to reverse words in a string 
s='Write a Python program to reverse words in a string'
s=s.split()
s=s[::-1]
d= ' '.join(s)
d

'string a in words reverse to program Python a Write'

In [28]:
# Write a Python program to swap cases of a given string
s='Python proGram To revErse wOrds'
a = s.swapcase()
print(a)

pYTHON PROgRAM tO REVeRSE WoRDS


In [33]:
# Write a Python program to remove spaces from a given string
s='Python program to remove spaces from'
a = s.split()
d = ''.join(a)
d

'Pythonprogramtoremovespacesfrom'

In [37]:
# Write a Python program to remove duplicate characters of a given string

s= 'roshan dabhere roshan dabhere roshan'
s1=''
for i in s:
    if i not in s1:
        s1 += i
print(s1)
    

roshan dbe


In [40]:
# Write a Python Program to find the area of a circle
PI = 3.142
r = int(input( 'enter the radius:-'))

area = PI * (r * r)
print(area)

enter the radius:- 8


201.088


In [41]:
# Python Program to find Sum of squares of first n natural numbers
n = 5
total = 0

for i in range(1, n + 1):
    total += i * i
print(total)

55


In [20]:
d1={'a':1,'b':2}
d2={'c':3,'b':3,'d':4}
d={}
for x in d1:
    d[x]=d1[x]
    if x in d2:
        d[x]=d1[x]+d2[x]
for x in d2:
    if x not in d1:
        d[x]=d2[x]
print(d)


{'a': 1, 'b': 5, 'c': 3, 'd': 4}


In [21]:
l=[10 ,30, 40 ,50 ,80 ,90 ,40 ,60 ,30]
remove=[40 ,30]
res=[]
for x in l:
    if x not in remove :
        res.append(x)
res

[10, 50, 80, 90, 60]

## Numpy

In [30]:
import numpy as np
import warnings
warnings.filterwarnings('ignore') 

In [31]:
num = np.random.randint(1,100,26)
num

array([59, 89, 55, 14, 88, 98, 78, 91,  2, 54, 41, 66, 93, 95, 42, 96, 43,
       38, 87, 69, 61,  5, 65, 71, 14, 99])

In [32]:
# Accending

In [33]:
num=np.sort(num)

In [35]:
num1 = sorted(num.tolist(), reverse=True)
print(num1)

[99, 98, 96, 95, 93, 91, 89, 88, 87, 78, 71, 69, 66, 65, 61, 59, 55, 54, 43, 42, 41, 38, 14, 14, 5, 2]


In [36]:
np.sort([2,3,0]) 

array([0, 2, 3])

### sorting column wise

In [42]:
np.sort([[2,3,0],
        [7,5,8]],axis = 1)

array([[0, 2, 3],
       [5, 7, 8]])

In [43]:
a= np.sort([[2,3,0],
           [7,5,8]])
a.sort(axis=1)
print(a)

[[0 2 3]
 [5 7 8]]


# sorting row wise

In [46]:
matrix = [[8,3,9],
         [1,5,0]]
np.sort(matrix, axis=0)

array([[1, 3, 0],
       [8, 5, 9]])

# 2. replacing any item in any array using indexing

In [47]:
array = np.array([16,17,2,5,7])
array[1]=100
array

array([ 16, 100,   2,   5,   7])

In [49]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
array[0][0]=100
array 

array([[100,  16,  17],
       [  2,   5,   3],
       [  7,   0,   8]])

In [ ]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
print(array[0:2,0:2])
array[0:2,0:2]=[[100,200],[300,400]]
array 

In [51]:
array = np.array([[21,16,17],
                 [2,5,3],
                 [7,0,8]])
print(array[0:2,0:2])
array [0:2,0:2] = [[100,200],[300,400]]
array

[[21 16]
 [ 2  5]]


array([[100, 200,  17],
       [300, 400,   3],
       [  7,   0,   8]])

In [18]:
import numpy as np

my_array = np.array([1, 2, np.nan, 4, np.nan, 6])

# Create a mask for NaN values
mask = np.isnan(my_array)

# Use the inverse of the mask to filter out missing values
filtered_array = my_array[~mask]

print("Original Array:", my_array)
print("Filtered Array (without NaNs):", filtered_array)

Original Array: [ 1.  2. nan  4. nan  6.]
Filtered Array (without NaNs): [1. 2. 4. 6.]


In [19]:
import numpy as np

my_array = np.array([1, 2, np.nan, 4, np.nan, 6])

# Create a mask for NaN values
mask = np.isnan(my_array)

# Use the inverse of the mask to filter out missing values
filtered_array = my_array[mask]

print("Original Array:", my_array)
print("Filtered Array (without NaNs):", filtered_array)

Original Array: [ 1.  2. nan  4. nan  6.]
Filtered Array (without NaNs): [nan nan]


## Pandas

In [12]:
import pandas as pd
list1 = ['g', 'e', 'e', 'k', 's']
print(pd.Series(list1))

0    g
1    e
2    e
3    k
4    s
dtype: object


In [13]:
import pandas as pd

dict = {'Geeks': 10,'for': 20, 'geeks': 30}

print(pd.Series(dict))

Geeks    10
for      20
geeks    30
dtype: int64


In [14]:
import pandas as pd

dict = {'Geeks': 10,'for': 20, 'geeks': 30}

print(pd.Series(dict))

Geeks    10
for      20
geeks    30
dtype: int64


In [1]:
import pandas as pd 

In [3]:
df = pd.read_csv('random_stock_market_dataset.csv')
df.head(5)

Date    Open    High     Low   Close  Volume
0  2024-01-01  296.45  307.31  293.96  303.72   93133
1  2024-01-02  190.11  193.10  187.21  191.40   64993
2  2024-01-03  197.41  208.64  193.37  205.89   70326
3  2024-01-04  253.13  262.67  248.67  258.95   17358
4  2024-01-05  241.35  253.09  238.99  252.20   20847

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    60 non-null     object 
 1   Open    60 non-null     float64
 2   High    60 non-null     float64
 3   Low     60 non-null     float64
 4   Close   60 non-null     float64
 5   Volume  60 non-null     int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 2.9+ KB


In [10]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64